// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFL3FHykOp5FV_fcEkCOY_PgKqBs1C-f8',
    appId: '1:977264982159:web:de6b59c56b28c493ca98fa',
    messagingSenderId: '977264982159',
    projectId: 'ember-f7f7a',
    authDomain: 'ember-f7f7a.firebaseapp.com',
    storageBucket: 'ember-f7f7a.firebasestorage.app',
    measurementId: 'G-31YWREXJ7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmshKt5zMcfOf84KdnXcqFBGHAOAlNEU8',
    appId: '1:977264982159:android:99e1dc4cf75c7bf2ca98fa',
    messagingSenderId: '977264982159',
    projectId: 'ember-f7f7a',
    storageBucket: 'ember-f7f7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2D1vOzYNT8xcMmLlk0YgQPeymRdMTBUs',
    appId: '1:977264982159:ios:1f70d890e716abe5ca98fa',
    messagingSenderId: '977264982159',
    projectId: 'ember-f7f7a',
    storageBucket: 'ember-f7f7a.firebasestorage.app',
    iosBundleId: 'com.example.ember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2D1vOzYNT8xcMmLlk0YgQPeymRdMTBUs',
    appId: '1:977264982159:ios:1f70d890e716abe5ca98fa',
    messagingSenderId: '977264982159',
    projectId: 'ember-f7f7a',
    storageBucket: 'ember-f7f7a.firebasestorage.app',
    iosBundleId: 'com.example.ember',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFL3FHykOp5FV_fcEkCOY_PgKqBs1C-f8',
    appId: '1:977264982159:web:7dd18f05e6691eebca98fa',
    messagingSenderId: '977264982159',
    projectId: 'ember-f7f7a',
    authDomain: 'ember-f7f7a.firebaseapp.com',
    storageBucket: 'ember-f7f7a.firebasestorage.app',
    measurementId: 'G-5H3VJHDFJY',
  );

}